### ISSUE TITLE
Python code?

### ISSUE THREAD

**Issue by andreped** [vipgugr/BKSVD#1]
It would definitely be of interest to have a python implementation of this approach, to test this method further. Does such an implementation exist?

**Comment by zalteck** [comment]
Hi andreped,

Unfortunately, the method uses some previous bayesian functions that are not implemented in python yet. Although we have considered implementing it in python in the future, it is on the schedule yet.

The only implementation available uses MATLAB.

Kind regards,
Fernando Pérez-Bueno

**Comment by zalteck** [comment]
A beta of the Python code is now implemented:

https://github.com/zalteck/BKSVD-Python

**Comment by andreped** [comment]
Cool, @zalteck! I can make a PR to add support to it to torchstain, if thats OK with you :]
https://github.com/EIDOSLAB/torchstain

But I will implement it to pure numpy, tensorflow, and pytorch implementations, without PIL, if thats doable.

**Comment by zalteck** [comment]
@andreped That's OK with us :) Please let me know how to help.

Implementing it without PIL is very doable. It is only used to load the images when using the Multi-Image approach.

**Comment by andreped** [comment]
Sounds good. I will go ahead and implement it some time this week. This is something I do on the side, so I dont have much time during work hours. Will let you know when I have a PR ready, and I could request you to review, if thats fine with you? :]

I will implement some tests as well, just to verify that it works and is compatible with all backends.
